### ISSUE TITLE
NodeJs v.6.0.0 introduces issue with cpexcel.js Buffer usage.

### ISSUE THREAD

**Issue by macyabbey** [SheetJS/js-codepage#12]
Setting the length property after construction of Buffer objects is no longer valid.

Reading an excel spreadsheet buffer yields:

TypeError: Cannot set property length of [object Object] which has only a getter
    at sbcs_d (.../node/node_modules/xlsx/dist/cpexcel.js:909:20)
    at Object.decode (.../node_modules/xlsx/dist/cpexcel.js:1197:40)
    at _gc2 (.../node/node_modules/xlsx/xlsx.js:28:24)
    at Buffer.ReadShift [as read_shift](.../node/node_modules/xlsx/xlsx.js:1611:13)
    at parse_XLUnicodeStringNoCch (.../node/node_modules/xlsx/xlsx.js:3113:23)
    at parse_XLUnicodeString (.../node/node_modules/xlsx/xlsx.js:3121:9)
    at parse_XLUnicodeString2 (.../node/node_modules/xlsx/xlsx.js:3125:48)
    at Object.parse_Format [as f](.../node/node_modules/xlsx/xlsx.js:3492:15)
    at slurp (.../node/node_modules/xlsx/xlsx.js:9229:11)
    at parse_workbook (.../node/node_modules/xlsx/xlsx.js:9350:15) +0ms
.../node/node_modules/xlsx/xlsx.js:9350:15)

Just removing the statement at line 909 seems to make everything work again, but not sure how safe this is without fully understanding the context.  Hoping someone with more knowledge of this library can provide the right fix.

**Comment by reviewher** [comment]
The relevant fixes have been committed here and pushed to both js-xlsx and js-xls.
